title: Cost competitiveness of blue and green Hydrogen
desc: Techno-economic analysis of the competitiveness of blue and green hydrogen production technologies based on temporal development of direct production cost and carbon cost computed from life-cycle emissions.
auth: Philipp C. Verpoort, Falko Ueckerdt, Rahul Anantharaman, Christian Bauer, Fiona Beck, Thomas Longden, Simon Roussanaly
date: 10/02/2022
