yaxislabel: Levelised Cost of Hydrogen in EUR/MWh

labels:
  cost__cap_cost: Capital cost
  cost__onm_cost: Operational and maintenance cost
  cost__fuel_cost: Fuel cost
  cost__cts_cost: Carbon transport and storage cost

colours:
  cost__cap_cost: '#db2a1a'
  cost__onm_cost: '#00813e'
  cost__fuel_cost: '#3745a3'
  cost__cts_cost: '#589ace'

fuels:
  - natural gas
  - blue HEB
  - blue LEB
  - green RE

years:
  - 2025
  - 2050
