plotting:
  carb_price_max: 800.0
  fuel_cost_max: 150.0
  numb_cols: 2

labels:
  CP: Carbon Pricing in EUR/t<sub>CO<sub>2</sub>eq</sub>
  total_cost: Total cost in EUR/MWh<sub>LHV</sub>

showFuels:
  - [[1, 2], 2020, natural gas]
  - [[1, 2], 2020, blue LEB]
  - [[1, 2], 2020, green RE]
  - [[2], 2050, green RE]

showFSCPs:
  - [[1, 2], 2020, natural gas, 2020, blue LEB]
  - [[1, 2], 2020, natural gas, 2020, green RE]
  - [[1, 2], 2020, blue LEB,    2020, green RE]
  - [[2],    2020, natural gas, 2050, green RE]
  - [[2],    2020, blue LEB,    2050, green RE]
