plotting:
  carb_price_max: 550.0
  fuel_cost_max: 150.0
  numb_cols: 2
  uncertainty: False

labels:
  CP: Carbon Pricing in EUR/t<sub>CO<sub>2</sub>eq</sub>
  total_cost: Total cost in EUR/MWh<sub>LHV</sub>

showFuels:
  - [[1, 2], 2025, natural gas]
  - [[1, 2], 2025, green RE]
  - [[1, 2], 2050, green RE]
  - [[1], 2025, blue HEB]
  - [[2], 2025, blue LEB]
  - [[2], 2050, blue LEB]

showFSCPs:
  - [[1], 2025, natural gas, 2025, green RE, 'circle-open']
  - [[1], 2025, natural gas, 2025, blue HEB, 'circle-open']
  - [[1], 2025, blue HEB, 2025, green RE, 'circle-open']
  - [[1], 2025, natural gas, 2050, green RE, 'x-thin']
  - [[1], 2025, blue HEB, 2050, green RE, 'x-thin']
  - [[2], 2025, blue LEB, 2050, green RE, 'circle-open']
  - [[2], 2050, blue LEB, 2050, green RE, 'circle-open']
  - [[2], 2025, natural gas, 2050, green RE, 'circle-open']
  - [[2], 2025, natural gas, 2025, blue LEB, 'circle-open']
  - [[2], 2025, natural gas, 2050, blue LEB, 'circle-open']
