plotting:
  ci_max: 0.215
  cost_max: 100.0
  n_samples: 51

labels:
  ci: Carbon Intensity (g<sub>CO<sub>2</sub>eq</sub>/kWh<sub>LHV</sub>)
  cost: Direct Cost (EUR/MWh<sub>LHV</sub>)

refFuel: natural gas
refYear: 2025

showFuels:
  - green RE
  - blue HEB
  - blue LEB
