plotting:
  ghgi_max_left: 0.225
  cost_max_left: 120.0
  ghgi_max_right: 0.700
  cost_max_right: 700.0
  n_samples: 301

labels:
  ghgiLeft: GHG Intensity (g<sub>CO<sub>2</sub>eq</sub>/kWh<sub>LHV</sub>)
  costLeft: Direct Cost (EUR/MWh<sub>LHV</sub>)
  ghgiRight: GHG Intensity (g<sub>CO<sub>2</sub>eq</sub>/t<sub>LS</sub>)
  costRight: Direct Cost (EUR/t<sub>LS</sub>)

subplot_title_positions:
  - [0.0, 1.1]
  - [0.5, 1.1]

refFuel: natural gas
refYear: 2025

showFuels:
  - green RE
  - green pure RE
  - blue HEB
  - blue LEB
