plotting:
  carb_price_max: 650.0
  fuel_cost_max: 200.0
  numb_cols: 2
  uncertainty: False

labels:
  CP: Carbon Pricing (EUR/t<sub>CO<sub>2</sub>eq</sub>)
  total_cost: Total cost (EUR/MWh<sub>LHV</sub>)

subplot_title_positions:
  - [0.0, 1.1]
  - [0.5, 1.1]

showFuels:
  - [[1, 2], 2025, natural gas]
  - [[1, 2], 2025, green RE]
  - [[1, 2], 2050, green RE]
  - [[1], 2025, blue HEB]
  - [[2], 2025, blue LEB]
  - [[2], 2050, blue LEB]

showFSCPs:
  - [[1], 2025, natural gas, 2025, green RE, 'circle-open']
  - [[1], 2025, natural gas, 2025, blue HEB, 'circle-open']
  - [[1], 2025, blue HEB, 2025, green RE, 'circle-open']
  - [[1], 2025, natural gas, 2050, green RE, 'x-thin']
  - [[1], 2025, blue HEB, 2050, green RE, 'x-thin']
  - [[2], 2025, blue LEB, 2025, green RE, 'circle-open']
  - [[2], 2050, blue LEB, 2050, green RE, 'circle-open']
  - [[2], 2025, natural gas, 2025, green RE, 'circle-open']
  - [[2], 2050, natural gas, 2050, green RE, 'circle-open']
  - [[2], 2025, natural gas, 2025, blue LEB, 'circle-open']
  - [[2], 2025, natural gas, 2050, blue LEB, 'circle-open']
