plotting:
  delta_x1: 10.0
  delta_x2: 300000.00
  delta_x3: 0.10
  delta_x4: 5.0
  delta_x5: 0.3e+8
  delta_cost: 15.0
  n_samples: 51

labels:
  x1: Electricity price<br>in EUR/kWh
  x2: Green GAPEX<br>in EUR/kW
  x3: Op. capacity factor<br>in %
  x4: Natural gas price<br>in EUR/MWh
  x5: Blue CAPEX<br>in MEUR/10^5 Nm^3/h
  cost: Cost difference in 2030<br>in EUR/MWh<sub>LHV</sub>

fuelBlue: blue LEB
fuelGreen: green RE
fuelYear: 2030
