plotting:
  t_min: 2023.5
  t_max: 2051.5
  fscp_min: -100.0
  fscp_max: 1000.0

labels:
  time: ''
  fscp: FSCP (EUR/t<sub>CO<sub>2</sub>eq</sub>)
  fscp_steel: FSCP (EUR/t<sub>CO<sub>2</sub>eq</sub>)

subplot_title_positions:
  - [0.0, 1.05]
  - [0.5, 1.05]
  - [0.0, 0.5]
  - [0.5, 0.5]
  
showFSCPs:
  - [[1, 2], ref, green RE]
  - [[1, 2], ref, green pure RE]
  - [[1], ref, blue HEB]
  - [[2], ref, blue LEB]
  - [[1], blue HEB, green RE]
  - [[2], blue LEB, green RE]
  - [[1], blue HEB, green pure RE]
  - [[2], blue LEB, green pure RE]

showAnnotations:
  left:
    - ref
    - green RE
    - blue HEB
  right:
    - ref
    - green RE
    - blue LEB

fscp_colours:
  blue HEB to green RE: '#dc291a'
  blue HEB to green pure RE: '#dc291a'
  blue LEB to green RE: '#fc4b32'
  blue LEB to green pure RE: '#fc4b32'

carbon_price_trajectory:
  time: [2020, 2030, 2050]
  value: [50.0, 130.0, 500.0]
  value_upper: [70.0, 210.0, 700.0]
  value_lower: [0.0, 50.0, 200.0]

carbon_price_config:
  name: 'CO<sub>2</sub>-Price'
  colour: '#7c2089'

refFuelTop: natural gas
refFuelBottom: blast furnace

n_samples: 1000
