plotting:
  fscp_max: 500.0
  numb_cols: 2

labels:
  time: ""
  fscp: FSCP in EUR/MWh<sub>LHV</sub>
  
showFSCPs:
  - [[1, 2], natural gas, green RE]
  - [[1], natural gas, blue HEB]
  - [[2], natural gas, blue LEB]
  - [[1], blue HEB, green RE]
  - [[2], blue LEB, green RE]

fscp_colours:
  blue HEB to green RE: '#dac367'
  blue LEB to green RE: '#ffdb4c'
