yaxislabel: Levelised Cost of Energy (EUR/MWh<sub>LHV</sub>)

ymax: 140.0

labels:
  cost__cap_cost: Capital cost
  cost__fuel_cost: Fuel cost (non-elec.)
  cost__elec_cost: Electricity cost
  cost__fonm_cost: Fixed Operation<br>and Maintenance Cost
  cost__vonm_cost: Variable Operation<br>and Maintenance Cost
  cost__cts_cost: Carbon transport<br>and storage cost
  cost__tra_cost: H<sub>2</sub> transport cost

colours:
  cost__cap_cost: '#f36f21'
  cost__elec_cost: '#e6af2e'
  cost__fuel_cost: '#3745a3'
  cost__fonm_cost: '#00813e'
  cost__vonm_cost: '#db2a1a'
  cost__cts_cost: '#589ace'
  cost__tra_cost: '#7c1f8a'

fuels:
  - natural gas
  - blue HEB
  - blue LEB
  - green RE

years:
  - 2025
  - 2050
