vertical_spacing: 0.3

plotting:
  n_samples: 301

  xaxis1_min: 0.010
  xaxis1_max: 0.200
  xaxis2_min: 0.00
  xaxis2_max: 0.05
  xaxis3_min: 0.00
  xaxis3_max: 0.05
  xaxis4_min: 0.77
  xaxis4_max: 1.00
  xaxis5_min: 0.91
  xaxis5_max: 1.00

  yaxis1_min: -10.0
  yaxis1_max: 70.0
  yaxis2_min:  0.0
  yaxis2_max: 25.0

labels:
  xaxis1: CI<sub>blue</sub> — CI<sub>green</sub> in g<sub>CO<sub>2</sub>eq</sub>/kWh<sub>LHV</sub>
  xaxis2: Methane leakage rate in %
  xaxis3: Methane leakage rate in %
  xaxis4: Share of renewable electricity in %
  xaxis5: Share of renewable electricity in %
  xaxis7: ''
  xaxis8: ''
  xaxis9: ''
  xaxis10: ''
  xaxis12: CI<sub>blue</sub> in g<sub>CO<sub>2</sub>eq</sub>/kWh<sub>LHV</sub>
  xaxis13: CI<sub>blue</sub> in g<sub>CO<sub>2</sub>eq</sub>/kWh<sub>LHV</sub>
  xaxis14: CI<sub>green</sub> in g<sub>CO<sub>2</sub>eq</sub>/kWh<sub>LHV</sub>
  xaxis15: CI<sub>green</sub> in g<sub>CO<sub>2</sub>eq</sub>/kWh<sub>LHV</sub>

  yaxis1: Cost<sub>green</sub> — Cost<sub>blue</sub> in EUR/MWh<sub>LHV</sub>

subplot_titles:
  - (a)
  - (b)
  - (c)
  - (d)
  - (e)

subplot_title_positions:
  - [0.01, 0.0]
  - [0.52, 0.65]
  - [0.775, 0.65]
  - [0.52, 0.0]
  - [0.775, 0.0]

linedensity:
  plot1: 100
  plot2: 25
  plot4: 50

colours:
  heatmap_high: '#345979'
  heatmap_medium: '#62b7fe'
  heatmap_low: '#00fe00'

fscp_colours:
  blue HEB to green RE: '#dac367'
  blue LEB to green RE: '#ffdb4c'

colourscale:
  FSCPmin: -100.0
  FSCPmax: 1000.0
  FSCPmid: 400.0

fuelGreen: green RE
fuelBlueLeft: blue HEB
fuelBlueRight: blue LEB
fuelYear: 2050
