yaxislabel: Levelised GHGI of Energy (g<sub>CO<sub>2</sub>eq</sub>/kWh<sub>LHV</sub>)

labels:
  ghgi__base: Base emissions
  ghgi__mleakage: Methane leakage
  ghgi__elec: Electricity

colours:
  ghgi__base: '#db2a1a'
  ghgi__mleakage: '#00813e'
  ghgi__elec: '#3745a3'

fuels:
  - natural gas
  - blue HEB
  - blue LEB
  - green RE

years:
  - 2025
  - 2050
