plotting:
  fscp_max: 500.0
  numb_cols: 2

labels:
  time: ""
  fscp: FSCP in EUR/MWh<sub>LHV</sub>
  
showFSCPs:
  - [[1, 2], natural gas, green RE]
  - [[1], natural gas, blue HEB]
  - [[2], natural gas, blue LEB]
  - [[1], blue HEB, green RE]
  - [[2], blue LEB, green RE]

fscp_colours:
  blue HEB to green RE: '#dac367'
  blue LEB to green RE: '#ffdb4c'

carbon_price_trajectory:
  time: [2020, 2030, 2050]
  value: [50.0, 130.0, 500.0]
  value_upper: [70.0, 210.0, 700.0]
  value_lower: [0.0, 50.0, 200.0]

carbon_price_config:
  name: 'CO<sub>2</sub>-Price'
  colour: '#006000'
