plotting:
  carb_price_max: 1200.0
  fuel_cost_max: 260.0
  numb_cols: 2

labels:
  fuel: Fuel Type
  year: ''
  CP: Carbon Pricing in €/t<sub>CO<sub>2</sub>eq</sub>
  total_cost: Total cost in €/MWh<sub>LHV</sub>
