plotting:
  ci_max_left: 0.225
  cost_max_left: 100.0
  ci_max_right: 0.700
  cost_max_right: 650.0
  n_samples: 301

labels:
  ciLeft: Carbon Intensity (g<sub>CO<sub>2</sub>eq</sub>/kWh<sub>LHV</sub>)
  costLeft: Direct Cost (EUR/MWh<sub>LHV</sub>)
  ciRight: Carbon Intensity (g<sub>CO<sub>2</sub>eq</sub>/t<sub>LS</sub>)
  costRight: Direct Cost (EUR/t<sub>LS</sub>)

subplot_title_positions:
  - [0.0, 1.1]
  - [0.5, 1.1]

refFuel: natural gas
refYear: 2025

showFuels:
  - green RE
  - green pure RE
  - blue HEB
  - blue LEB
