print:
    lw_default: 5
    lw_thin: 3
    lw_ultrathin: 0.6
    highlight_marker: 24
    highlight_marker_sm: 12
    fs_lg: 7
    fs_md: 6
    fs_sm: 5
    fs_tn: 4
webapp:
    lw_default: 2.5
    lw_thin: 1.5
    lw_ultrathin: 0.4
    highlight_marker: 16
    highlight_marker_sm: 8
    fs_lg: 5
    fs_md: 4
    fs_sm: 3
    fs_tn: 2
