figures:
  figS3:
    name: Figure S3
    title: ' '
    desc: 'Extended data figure not included in manuscript.'
    size:
      print:
        width: 172.0  # unit mm
        height: 100.0  # unit mm
      webapp:
        width: 100.0  # unit %
        height: 600.0  # unit px
config:
  vertical_spacing: 0.3

  plotting:
    n_samples: 301

    xaxis1_min: 0.000
    xaxis1_max: 0.190
    xaxis2_min: 0.00
    xaxis2_max: 0.03
    xaxis3_min: 0.00
    xaxis3_max: 0.03
    xaxis4_min: 0.80
    xaxis4_max: 1.00
    xaxis5_min: 0.80
    xaxis5_max: 1.00

    yaxis1_min: -30.0
    yaxis1_max: 100.0
    yaxis2_min: -10.0
    yaxis2_max: 40.0

  labels:
    xaxis1: GHG Intensity<sub>Blue H<sub>2</sub></sub> - GHG Intensity<sub>Green H<sub>2</sub></sub> (g<sub>CO<sub>2</sub>eq</sub>/kWh<sub>LHV</sub>)
    xaxis2: Methane leakage rate (%<sup>GWP100</sup>)
    xaxis3: Methane leakage rate (%<sup>GWP100</sup>)
    xaxis4: Share of renewable electricity (%)
    xaxis5: Share of renewable electricity (%)
    xaxis7: <sub>GWP20</sub>
    xaxis8: <sub>GWP20</sub>
    xaxis9: ''
    xaxis10: ''
    xaxis12: GHG Intensity<sub>Blue H<sub>2</sub></sub> (g<sub>CO<sub>2</sub>eq</sub>/kWh<sub>LHV</sub>)
    xaxis13: GHG Intensity<sub>Blue H<sub>2</sub></sub> (g<sub>CO<sub>2</sub>eq</sub>/kWh<sub>LHV</sub>)
    xaxis14: GHG Intensity<sub>Green H<sub>2</sub></sub> (g<sub>CO<sub>2</sub>eq</sub>/kWh<sub>LHV</sub>)
    xaxis15: GHG Intensity<sub>Green H<sub>2</sub></sub> (g<sub>CO<sub>2</sub>eq</sub>/kWh<sub>LHV</sub>)

    yaxis1: Cost<sub>Green H<sub>2</sub></sub> - Cost<sub>Blue H<sub>2</sub></sub> (EUR/MWh<sub>LHV</sub>)

  subplot_title_positions:
    - [0.0  , 1.1]
    - [0.5, 1.1]
    - [0.75, 1.1]
    - [0.5, 0.5]
    - [0.75, 0.5]

  linedensity:
    plot1: 100
    plot2: 25
    plot3: 50
    plot4: 50
    plot5: 100

  colours:
    heatmap_high: '#3647a3'
    heatmap_medium: '#589ACE'
    heatmap_low: '#6ac100'

  fscp_colour:
    cons-cons: '#dc291a'
    cons-prog: '#d63ff6'
    prog-cons: '#bb1adc'
    prog-prog: '#fc4b32'

  colourscale:
    FSCPmin: -200.0
    FSCPmax: 1200.0
    FSCPmid: 400.0

  fuelsScatterGreen:
      - GREEN-cons
      - GREEN-prog

  fuelsScatterBlue:
      - BLUE-high-cons
      - BLUE-high-prog
      - BLUE-low-cons
      - BLUE-low-prog

  showYearNumbers:
    - 2025
    - 2035
    - 2050

  fuelGreen: GREEN-prog
  fuelBlueLeft: BLUE-high-cons
  fuelBlueRight: BLUE-high-prog
  fuelYearTop: 2035
  fuelYearBottom: 2030

  show_errorbars: False
