figures:
  fig3:
    name: Figure 3
    title: Estimating fuel-switching points in time based on fuel-switching CO2 prices
    desc:
      'Same as conceptual Figure 2C, now estimated for four cases derived by combining technology cases (top,
       conservative; bottom, progressive) with natural gas prices (left, high; right, low). From the intersections of 
      FSCPs in time, fuel-switching points can be derived that determine the improving competitiveness of hydrogen with 
      fossil fuels as well as the increasing competitiveness of green hydrogen with blue hydrogen.'
    display:
    - ''
    size:
      print:
        width: 172.0  # unit mm
        height: 122.0  # unit mm
      webapp:
        width: 100.0  # unit %
        height: 900.0  # unit px
  figS5:
    name: Figure S5
    title: Fuel-switching CO2 prices (FSCP) in time
    desc:
      'Same as Figure 3 but reduced to only FSCP of green and blue hydrogen (with natural gas) also including 
      uncertainty ranges from parameter variations of 5%. The four cases are derived by combining technology cases 
      (top: conservative, bottom: progressive) with natural gas prices (left: high, right: low).'
    display:
    - 'supplementary'
    size:
      print:
        width: 172.0  # unit mm
        height: 100.0  # unit mm
      webapp:
        width: 100.0  # unit %
        height: 740.0  # unit px
config:
  plotting:
    t_min: 2023.5
    t_max: 2051.5
    fscp_min: -100.0
    fscp_max: 1000.0
    fscp_unc_min: -100.0
    fscp_unc_max: 1000.0

  labels:
    time: ''
    fscp: Fuel-switching CO<sub>2</sub> price (EUR/t<sub>CO<sub>2</sub>eq</sub>)

  legendlabels:
    - Switching between natural gas and H<sub>2</sub>
    - Switching between H<sub>2</sub>-supply options
    - Policy instrument driving the fuel switch

  selected_cases:
    high-cons:
      - NG-high-cons
      - BLUE-high-cons
      - GREEN-cons
    low-cons:
      - NG-low-cons
      - BLUE-low-cons
      - GREEN-cons
    high-prog:
      - NG-high-prog
      - BLUE-high-prog
  #    - BLUE-high-prog-lowscco2
      - GREEN-prog
    low-prog:
      - NG-low-prog
      - BLUE-low-prog
  #    - BLUE-low-prog-lowscco2
      - GREEN-prog

  show_cp_unc: False
  bgfscp_unc: False

  selected_cases_labels:
    high-cons: High gas price, conservative
    low-cons: Low gas price, conservative
    high-prog: High gas price, progressive
    low-prog: Low gas price, progressive

  cases_dashed:
    - BLUE-high-prog-lowscco2
    - BLUE-low-prog-lowscco2

  sidelabels:
    top:
      - <b>High gas prices</b><br>60 EUR/MWh<sub>LHV</sub> in 2025, 40 EUR/MWh<sub>LHV</sub> from 2030 onward
      - <b>Low gas prices</b><br>15 EUR/MWh<sub>LHV</sub> throughout
    left:
      - <b>Conservative assumptions</b>
      - <b>Progressive assumptions</b>

  annotationTexts:
    heading1: Fuel-switching points that capture the expanding competitiveness of low-carbon H<sub>2</sub> with fossil applications
    heading2: Fuel-switching points that capture the inversion of competitiveness within the H<sub>2</sub> supply, such that green H<sub>2</sub> becomes the most competitive option
    point1: Blue H<sub>2</sub> becomes competitive with natural gas<br>due to CO<sub>2</sub> pricing or equivalent regulation
    point2: Green H<sub>2</sub> becomes competitive with natural gas<br>due to CO<sub>2</sub> pricing or equivalent regulation
    point3: Green H<sub>2</sub> becomes cheaper than blue H<sub>2</sub><br>due to high CO<sub>2</sub> pricing or equivalent regulation
    point4: Green H<sub>2</sub> becomes the cheaper mitigation option<br>irrespective of CO<sub>2</sub> prices
    point5: Direct costs of green H<sub>2</sub> fall below<br>those of blue H<sub>2</sub>

  spacings:
    yShareTop: 0.62
    spacingTop: 0.07
    annotationsLegendWidth: 0.9
    annotationsLegendHeight: 0.18
    legendPosY: 0.33

  fscp_colour:
    cons-cons: '#dc291a'
    cons-prog: '#d63ff6'
    prog-cons: '#bb1adc'
    prog-prog: '#fc4b32'

  carbon_price_config:
    name: CO<sub>2</sub> price
    colour: '#7c2089'

  n_samples: 1000
