figures:
  fig4:
    name: Figure 4
    title: Fuel-switching CO<sub>2</sub> prices as a function of costs and residual emissions
    desc:
      (A and B) Emission intensities (x axis) and direct costs (y axis) of different hydrogen fuel options (scatter 
      plot for several years), along with FSCP estimates (contour plot) required to make hydrogen competitive with 
      natural gas for (A) high natural gas prices and (B) low natural gas prices. In addition to the progressive and 
      conservative technology cases, we here include a sensitivity case with very high upstream CO2 emission 
      reductions, which reflects the high ambitions of the oil and gas industry in Norway, dotted). We use GWP100 here. 
      For a sensitivity case with GWP 20, see Figure S6.
    display:
    - ''
    subfigs:
      fig4A:
        size:
          print:
            width: 86.0  # unit mm
            height: 100.0  # unit mm
          webapp:
            width: 50.0  # unit %
            height: 700.0  # unit px
      fig4B:
        size:
          print:
            width: 86.0  # unit mm
            height: 100.0  # unit mm
          webapp:
            width: 50.0  # unit %
            height: 700.0  # unit px
  figED2:
    name: Figure ED2
    title: Fuel-switching CO<sub>2</sub> prices as a function of costs and residual emissions for steel
    desc: Extended data figure not included in manuscript. Same as Figure 4, but with steel as an application.
    subfigs:
      figED2A:
        size:
          print:
            width: 86.0  # unit mm
            height: 100.0  # unit mm
          webapp:
            width: 50.0  # unit %
            height: 600.0  # unit px
      figED2B:
        size:
          print:
            width: 86.0  # unit mm
            height: 100.0  # unit mm
          webapp:
            width: 50.0  # unit %
            height: 600.0  # unit px
config:
  plotting:
    heating:
      ghgi_max: 0.23
      cost_max: 205.0
      zmax: 500
      zdticks: 100
      zdeltalines: 50.0
    steel:
      ghgi_max: 0.23
      cost_max: 700.0
      zmax: 200
      zdticks: 25
      zdeltalines: 25.0
    n_samples: 301

  labels:
    heating:
      ghgi: GHG Intensity (g<sub>CO<sub>2</sub>eq</sub>/kWh<sub>LHV</sub>)
      cost: Direct Cost (EUR/MWh<sub>LHV</sub>)
    steel:
      ghgi: GHG Intensity (t<sub>CO<sub>2</sub>eq</sub>/t<sub>LS</sub>)
      cost: Direct Cost (EUR/t<sub>LS</sub>)

  annotationLabels:
    left: <b>High gas prices</b><br>60 EUR/MWh<sub>LHV</sub> in 2025, 40 EUR/MWh<sub>LHV</sub> from 2030 onward
    right: <b>Low gas prices</b><br>15 EUR/MWh<sub>LHV</sub> throughout

  baselineLabels:
    heating: Price of natural gas
    steel: Cost of BF/BOF-Steel

  steelAssumptions:
    idreaf_demand_h2: 1.91 # H2 demand of H-DR in MWh_H2LHV / t_LS
    idreaf_cost: 457.0 # Other production cost in DR route in EUR / t_LS
    bfbof_cost: 389.0 # Blast furnace cost in EUR / t_LS
    bfbof_ghgi: 1.8 # Blast furnace GHGI in tCO2eq / t_LS

  thickLines:
    heating:
      left:
        - size: 100
          start: 100
          end: 600
        - size: 250
          start: 750
          end: 1000
        - size: 300
          start: 1200
          end: 1500
      right:
        - size: 100
          start: 100
          end: 600
        - size: 250
          start: 750
          end: 1000
        - size: 300
          start: 1200
          end: 1500
    steel:
      left:
        - size: 100
          start: 100
          end: 300
      right:
        - size: 100
          start: 100
          end: 300

  refFuel:
    left: NG-high-cons
    right: NG-low-cons

  refYear:
    left: 2030
    right: 2030

  showFuels:
    left:
      - BLUE-high-cons
      - BLUE-high-prog
      - BLUE-high-prog-lowscco2
      - GREEN-cons
      - GREEN-prog
      - GREEN-cons
      - GREEN-prog
    right:
      - BLUE-low-cons
      - BLUE-low-prog
      - BLUE-low-prog-lowscco2
      - GREEN-cons
      - GREEN-prog
      - GREEN-cons
      - GREEN-prog

  showYears:
    - 2025
    - 2030
    - 2035
    - 2040
    - 2045
    - 2050

  tokensDashed:
    - lowscco2
    - ME
